services:
  n8n-blog:
    image: n8nio/n8n
    ports:
      - "1978:5678"
    volumes:
      - n8n-rocketseat:/var/lib/n8n-blog
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
    restart: unless-stopped
    networks:
      - n8n-blog
volumes:
  n8n-blog:
networks:
  n8n-blog:
    driver: bridge
